sjkummer/janus-gateway-js

src/janus-connection.js
src/janus-session.js
test/janus-session.js

JanusSession specs

---

.travis.yml
README.md
package.json

After tests are done and merged

add test coverage

---

src/plugin.js
src/session.js
src/websocket-connection.js
test/session.js

on Connection `close` event -> trigger `destroy` event on each Session
on Session `destroy` event -> trigger `detach` event on each Plugin

Delegate destroy/close events down

---

README.md
src/client.js
src/connection.js
src/error.js
src/helpers.js
src/plugin.js
src/session.js
src/timer.js
src/traits/t-event-emitter.js
src/traits/t-transaction-gateway.js
src/transaction.js
src/transactions.js
src/websocket-connection.js

- Reference main janus-gateway project
- Main classes (connection, session, plugin)
- Explain events (bubbling)
- Example usages

Add Readme

---

src/websocket-connection.js

Current way of `webSocket instanceof WebSocket` does not work in browsers :(

Change W3cWebsocket detection in WebsocketConnection

---

src/error.js
src/helpers.js
test/helpers.js

To minimize the output dist file.

Use simple inheritance or extract util.inherits to some helper.

---

src/client.js
src/connection.js
test/connection.js
test/plugin.js
test/session.js

Use `Helpers.extend` for all passing of `options`.

Add `address` as parameter to Connection constructor

---

src/client.js
test/client.js

Add Client specs

---

src/client.js
test/client.js

Client.createConnection should resolve with an instance of Connection

---

gulpfile.js
package.json

Add a minifier to the build

---

test/connection.js
test/session.js
test/traits/t-event-emitter.js
test/traits/t-transaction-gateway.js

TransactionGateway, EventEmitter.

Add tests for Traits.

---

examples/browser/audiobridge.html
src/webrtc/media-plugin.js
src/webrtc/plugin/audiobridge-plugin.js

'addstream' => 'pc:track'
_onTrickle 'error' => 'pc:error'

Rename peer connection events

---

.travis.yml
LICENSE
README.md

- Run tests locally 
- Release a new version
See https://github.com/cargomedia/guides/tree/master/software-projects

Add docu about testing and releasing

---

README.md
Vagrantfile
package.json
puppet/Puppetfile
puppet/environments/development/manifests/site.pp
puppet/environments/development/modules/chrome/templates/install.sh.erb
puppet/environments/development/modules/npm_install/templates/npm_install.sh.erb
test/integration/audiobridge.js
test/integration/audioroom.js
test/integration/config.json
test/integration/karma.readJSON.js
test/integration/rtpbroadcast.js
test/integration/streaming.js
test/karma.conf.js

Install chrome 51 and later

---

.editorconfig
CONTRIBUTING.md

Contributing guide

---

README.md
package.json

Also to think. Shall we move plugins outside to their separate repos?

Create mechanism to hook plugins from outside

---

puppet/Puppetfile
puppet/environments/development/manifests/site.pp

Depends on https://github.com/cargomedia/puppet-packages/pull/1468

Update puppet env module usage

---

README.md
src/connection.js
src/plugin.js
src/session.js

@njam @zazabe please your opinion

Shall we emit 'detach' on plugins if somehow session is destroyed?

---

README.md

add unmaintained note

---

src/session.js

micro pr implementing an optional attachPlugin parameter passing an opaqueId to a plugin session

attachPlugin optional opaqueId parameter
